version: '3'

services:
    hackathon-web:
        container_name: hackathon-web
        image: ghcr.io/xd33m/mocca-hackathon:latest
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.hackathon-web.entrypoints: https
            traefik.http.services.hackathon-web.loadbalancer.server.port: 3000
            traefik.http.routers.hackathon-web.rule: Host(`hackathon.lucask.dev`)
        networks:
            - web

    hackathon-server:
            container_name: hackathon-server
            image: ghcr.io/xd33m/hackathon-server:latest
            environment:
                - OPENAI_API_KEY=${OPENAI_API_KEY}
                - ENV=${ENV}
            restart: unless-stopped
            labels:
                traefik.enable: true
                traefik.http.routers.hackathon-server.entryPoints: https
                traefik.http.services.hackathon-server.loadbalancer.server.port: 3000
                traefik.http.routers.hackathon-server.rule: (Host(`hackathon.lucask.dev`) && PathPrefix(`/api`))
            networks:
                - web
networks:
  web:
    external: true